# -*- coding: utf-8 -*-
"""mhp deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ceJs80asTVn4c7SuDBeJBmlmiMS8RrGP
"""

import streamlit as st
import pandas as pd
import joblib

model=joblib.load("mumbai house price data1 model (2).pkl")
encoder=joblib.load("label_encoder (2).pkl")

st.title("Mumbai house price app")

Title = st.selectbox("title",encoder["title"].classes_)
price =st.number_input("price")
area=st.number_input("area")
price_per_sqft=st.number_input("price_per_sqft")
locality=st.selectbox("locality",encoder["locality"].classes_)
city=st.selectbox("city",encoder["city"].classes_)
property_type=st.selectbox("property_type",encoder["property_type"].classes_)
bedroom_num=st.number_input("bedroom_num")
bathroom_num=st.number_input("bathroom_num")
balcony_num=st.number_input("balcony_num")
furnished=st.selectbox("furnished",encoder["furnished"].classes_)
age=st.number_input("age")
total_floors=st.number_input("total_floors")
latitude=st.number_input("latitude")
longitude=st.number_input("longitude")

df=pd.DataFrame({
    "Title":[Title],
    "price":[price],
    "area":[area],
    "price_per_sqft":[price_per_sqft],
    "locality":[locality],
    "city":[city],
    "property_type":[property_type],
    "bedroom_num":[bedroom_num],
    "bathroom_num":[bathroom_num],
    "balcony_num":[balcony_num],
    "furnished":[furnished],
    "age":[age],
    "total_floors":[total_floors],
    "latitude":[latitude],
    "longitude":[longitude]

})
if st.button("Predict"):
  for col in encoder:
    df[col]=encoder[col].transform(df[col])
Prediction=model.predict(df)
st.success(f"Mumbai house price data: {Prediction[0]:,.2f}")
